export const keywords = [
  { id: 'sharpsight', name: 'Бдительность', icons: ['sharpsight.png'] },
  { id: 'silence', name: 'Безмолвие', icons: ['silence.png'] },
  { id: 'gloom', name: 'Безысходность', icons: ['gloom.png'] },
  { id: 'hallowed', name: 'Благой', icons: ['hallowed.png'] },
  { id: 'quick_attack', name: 'Быстрая атака', icons: ['quickattack.png'] },
  { id: 'lifesteal', name: 'Вампиризм', icons: ['lifesteal.png'] },
  { id: 'regeneration', name: 'Восстановление', icons: ['regeneration.png'] },
  { id: 'brash', name: 'Вспыльчивость', icons: ['brash.png'] },
  { id: 'challenger', name: 'Выбор противника', icons: ['challenger.png'] },
  { id: 'deep', name: 'Глубина', icons: ['deep.png'] },
  { id: 'formidable', name: 'Громадный', icons: ['formidable.png'] },
  { id: 'double_attack', name: 'Двойная атака', icons: ['doublestrike.png'] },
  { id: 'fated', name: 'Избранный', icons: ['fated.png'] },
  { id: 'frostbite', name: 'Заморозка', icons: ['frostbite.png'] },
  { id: 'elusive', name: 'Изворотливость', icons: ['elusive.png'] },
  { id: 'fleeting', name: 'Мимолетность', icons: ['fleeting.png'] },
  { id: 'spirit', name: 'Мужество', icons: ['spirit.png'] },
  { id: 'cannot_attack', name: 'Не атакует', icons: ['cant_attack.png'] },
  { id: 'cannot_block', name: 'Не блокирует', icons: ['cant_block.png'] },
  { id: 'immobile', name: 'Неподвижность', icons: ['cant_attack.png', 'cant_block.png'] },
  { id: 'invulnerable', name: 'Неуязвимость', icons: ['blockade.png'] },
  { id: 'stunned', name: 'Оглушение', icons: ['stunned.png'] },
  { id: 'countdown', name: 'Отсчет', icons: ['countdown.svg'] },
  { id: 'lurk', name: 'Охота', icons: ['lurk.png'] },
  { id: 'deathless', name: 'Посмертие', icons: ['deathless.png'] },
  { id: 'attach', name: 'Прикрепление', icons: ['attach.png'] },
  { id: 'overwhelm', name: 'Пробивание', icons: ['overwhelm.png'] },
  { id: 'scout', name: 'Разведка', icons: ['scout.png'] },
  { id: 'tough', name: 'Стойкость', icons: ['tough.png'] },
  { id: 'impact', name: 'Таран', icons: ['impact.png'] },
  { id: 'augment', name: 'Улучшение', icons: ['augment.png'] },
  { id: 'fearsome', name: 'Устрашение', icons: ['fearsome.png'] },
  { id: 'vulnerable', name: 'Уязвимость', icons: ['vulnerable.png'] },
  { id: 'barrier', name: 'Щит', icons: ['barrier.png'] },
  { id: 'spellshield', name: 'Щит от магии', icons: ['spellshield.png'] },
  { id: 'evolve', name: 'Эволюция', icons: ['evolve.png'] },
  { id: 'attune', name: 'Эзотерика', icons: ['attune.png'] },
  { id: 'ephemeral', name: 'Эфемерность', icons: ['ephemeral.png'] },
  { id: 'fury', name: 'Ярость', icons: ['fury.png'] },
] as const

export type KeywordId = (typeof keywords)[number]['id']
export type KeywordDefinition = (typeof keywords)[number]
export type KeywordImages = Readonly<Record<string, HTMLImageElement>>
